# Generated by Django 5.1.7 on 2025-03-31 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_owner_alter_listing_price_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
