# Generated by Django 5.2 on 2025-04-09 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post_like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_like',
        ),
        migrations.AddField(
            model_name='like',
            name='post_liked',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_liked', to='network.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user_liking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_liking', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
